// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// adaptive_mh_ang_vol
Rcpp::List adaptive_mh_ang_vol(const arma::vec& angles, const arma::vec& sum_term, const arma::vec& sqrt_term, const int& dim, const double& starting_theta_ang, std::string ang_gauge_type, Rcpp::Nullable<double> prop_Sigma_angles_, const int& n_updates, const int& update_freq, const int& n_burnin, const int& n_thin, const bool& adapt_cov, const double& r_opt, const double& c0, const double& c1, const int& K);
RcppExport SEXP _gaugeDep_adaptive_mh_ang_vol(SEXP anglesSEXP, SEXP sum_termSEXP, SEXP sqrt_termSEXP, SEXP dimSEXP, SEXP starting_theta_angSEXP, SEXP ang_gauge_typeSEXP, SEXP prop_Sigma_angles_SEXP, SEXP n_updatesSEXP, SEXP update_freqSEXP, SEXP n_burninSEXP, SEXP n_thinSEXP, SEXP adapt_covSEXP, SEXP r_optSEXP, SEXP c0SEXP, SEXP c1SEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type angles(anglesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sum_term(sum_termSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sqrt_term(sqrt_termSEXP);
    Rcpp::traits::input_parameter< const int& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const double& >::type starting_theta_ang(starting_theta_angSEXP);
    Rcpp::traits::input_parameter< std::string >::type ang_gauge_type(ang_gauge_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type prop_Sigma_angles_(prop_Sigma_angles_SEXP);
    Rcpp::traits::input_parameter< const int& >::type n_updates(n_updatesSEXP);
    Rcpp::traits::input_parameter< const int& >::type update_freq(update_freqSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_burnin(n_burninSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_thin(n_thinSEXP);
    Rcpp::traits::input_parameter< const bool& >::type adapt_cov(adapt_covSEXP);
    Rcpp::traits::input_parameter< const double& >::type r_opt(r_optSEXP);
    Rcpp::traits::input_parameter< const double& >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const double& >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_mh_ang_vol(angles, sum_term, sqrt_term, dim, starting_theta_ang, ang_gauge_type, prop_Sigma_angles_, n_updates, update_freq, n_burnin, n_thin, adapt_cov, r_opt, c0, c1, K));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_mh_rad_ang_vol
Rcpp::List adaptive_mh_rad_ang_vol(const arma::vec& radii, const arma::vec& angles, const arma::vec& threshold, const arma::vec& sum_term, const arma::vec& sqrt_term, const int& dim, const arma::rowvec& starting_theta_rad, const double& starting_theta_ang, std::string rad_gauge_type, std::string ang_gauge_type, Rcpp::Nullable<Rcpp::NumericMatrix> prop_Sigma_radii_, Rcpp::Nullable<double> prop_Sigma_angles_, const int& n_updates, const int& update_freq, const int& n_burnin, const int& n_thin, const bool& adapt_cov, const double& r_opt, const double& c0, const double& c1, const int& K);
RcppExport SEXP _gaugeDep_adaptive_mh_rad_ang_vol(SEXP radiiSEXP, SEXP anglesSEXP, SEXP thresholdSEXP, SEXP sum_termSEXP, SEXP sqrt_termSEXP, SEXP dimSEXP, SEXP starting_theta_radSEXP, SEXP starting_theta_angSEXP, SEXP rad_gauge_typeSEXP, SEXP ang_gauge_typeSEXP, SEXP prop_Sigma_radii_SEXP, SEXP prop_Sigma_angles_SEXP, SEXP n_updatesSEXP, SEXP update_freqSEXP, SEXP n_burninSEXP, SEXP n_thinSEXP, SEXP adapt_covSEXP, SEXP r_optSEXP, SEXP c0SEXP, SEXP c1SEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type angles(anglesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sum_term(sum_termSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sqrt_term(sqrt_termSEXP);
    Rcpp::traits::input_parameter< const int& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type starting_theta_rad(starting_theta_radSEXP);
    Rcpp::traits::input_parameter< const double& >::type starting_theta_ang(starting_theta_angSEXP);
    Rcpp::traits::input_parameter< std::string >::type rad_gauge_type(rad_gauge_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type ang_gauge_type(ang_gauge_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type prop_Sigma_radii_(prop_Sigma_radii_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type prop_Sigma_angles_(prop_Sigma_angles_SEXP);
    Rcpp::traits::input_parameter< const int& >::type n_updates(n_updatesSEXP);
    Rcpp::traits::input_parameter< const int& >::type update_freq(update_freqSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_burnin(n_burninSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_thin(n_thinSEXP);
    Rcpp::traits::input_parameter< const bool& >::type adapt_cov(adapt_covSEXP);
    Rcpp::traits::input_parameter< const double& >::type r_opt(r_optSEXP);
    Rcpp::traits::input_parameter< const double& >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const double& >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_mh_rad_ang_vol(radii, angles, threshold, sum_term, sqrt_term, dim, starting_theta_rad, starting_theta_ang, rad_gauge_type, ang_gauge_type, prop_Sigma_radii_, prop_Sigma_angles_, n_updates, update_freq, n_burnin, n_thin, adapt_cov, r_opt, c0, c1, K));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_mh
Rcpp::List adaptive_mh(const arma::vec& radii, const arma::vec& angles, const arma::rowvec& starting_theta, std::string gauge_type, Rcpp::Nullable<Rcpp::NumericMatrix> prop_Sigma_, const int& n_updates, const int& update_freq, const int& n_burnin, const int& n_thin, const bool& adapt_cov, const double& r_opt, const double& c0, const double& c1, const int& K);
RcppExport SEXP _gaugeDep_adaptive_mh(SEXP radiiSEXP, SEXP anglesSEXP, SEXP starting_thetaSEXP, SEXP gauge_typeSEXP, SEXP prop_Sigma_SEXP, SEXP n_updatesSEXP, SEXP update_freqSEXP, SEXP n_burninSEXP, SEXP n_thinSEXP, SEXP adapt_covSEXP, SEXP r_optSEXP, SEXP c0SEXP, SEXP c1SEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type angles(anglesSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type starting_theta(starting_thetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type gauge_type(gauge_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type prop_Sigma_(prop_Sigma_SEXP);
    Rcpp::traits::input_parameter< const int& >::type n_updates(n_updatesSEXP);
    Rcpp::traits::input_parameter< const int& >::type update_freq(update_freqSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_burnin(n_burninSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_thin(n_thinSEXP);
    Rcpp::traits::input_parameter< const bool& >::type adapt_cov(adapt_covSEXP);
    Rcpp::traits::input_parameter< const double& >::type r_opt(r_optSEXP);
    Rcpp::traits::input_parameter< const double& >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const double& >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_mh(radii, angles, starting_theta, gauge_type, prop_Sigma_, n_updates, update_freq, n_burnin, n_thin, adapt_cov, r_opt, c0, c1, K));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _gaugeDep_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _gaugeDep_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _gaugeDep_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _gaugeDep_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}
// rmultinom_1
arma::vec rmultinom_1(const arma::vec& arma_probs);
RcppExport SEXP _gaugeDep_rmultinom_1(SEXP arma_probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type arma_probs(arma_probsSEXP);
    rcpp_result_gen = Rcpp::wrap(rmultinom_1(arma_probs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gaugeDep_adaptive_mh_ang_vol", (DL_FUNC) &_gaugeDep_adaptive_mh_ang_vol, 16},
    {"_gaugeDep_adaptive_mh_rad_ang_vol", (DL_FUNC) &_gaugeDep_adaptive_mh_rad_ang_vol, 21},
    {"_gaugeDep_adaptive_mh", (DL_FUNC) &_gaugeDep_adaptive_mh, 14},
    {"_gaugeDep_rcpparma_hello_world", (DL_FUNC) &_gaugeDep_rcpparma_hello_world, 0},
    {"_gaugeDep_rcpparma_outerproduct", (DL_FUNC) &_gaugeDep_rcpparma_outerproduct, 1},
    {"_gaugeDep_rcpparma_innerproduct", (DL_FUNC) &_gaugeDep_rcpparma_innerproduct, 1},
    {"_gaugeDep_rcpparma_bothproducts", (DL_FUNC) &_gaugeDep_rcpparma_bothproducts, 1},
    {"_gaugeDep_rmultinom_1", (DL_FUNC) &_gaugeDep_rmultinom_1, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_gaugeDep(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
