// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// angular_vol_adaptive_mh
Rcpp::List angular_vol_adaptive_mh(const arma::vec& angles, const arma::mat& grid_x, const int& dim, const arma::rowvec& starting_theta, std::string gauge_type, Rcpp::Nullable<Rcpp::NumericMatrix> prop_Sigma_, const int& n_updates, const int& update_freq, const int& n_burnin, const int& n_thin, const bool& adapt_cov, const double& r_opt, const double& c0, const double& c1, const int& K);
RcppExport SEXP _gaugeDependence_angular_vol_adaptive_mh(SEXP anglesSEXP, SEXP grid_xSEXP, SEXP dimSEXP, SEXP starting_thetaSEXP, SEXP gauge_typeSEXP, SEXP prop_Sigma_SEXP, SEXP n_updatesSEXP, SEXP update_freqSEXP, SEXP n_burninSEXP, SEXP n_thinSEXP, SEXP adapt_covSEXP, SEXP r_optSEXP, SEXP c0SEXP, SEXP c1SEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type angles(anglesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type grid_x(grid_xSEXP);
    Rcpp::traits::input_parameter< const int& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type starting_theta(starting_thetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type gauge_type(gauge_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type prop_Sigma_(prop_Sigma_SEXP);
    Rcpp::traits::input_parameter< const int& >::type n_updates(n_updatesSEXP);
    Rcpp::traits::input_parameter< const int& >::type update_freq(update_freqSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_burnin(n_burninSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_thin(n_thinSEXP);
    Rcpp::traits::input_parameter< const bool& >::type adapt_cov(adapt_covSEXP);
    Rcpp::traits::input_parameter< const double& >::type r_opt(r_optSEXP);
    Rcpp::traits::input_parameter< const double& >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const double& >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(angular_vol_adaptive_mh(angles, grid_x, dim, starting_theta, gauge_type, prop_Sigma_, n_updates, update_freq, n_burnin, n_thin, adapt_cov, r_opt, c0, c1, K));
    return rcpp_result_gen;
END_RCPP
}
// gauss_gauge
arma::vec gauss_gauge(const arma::vec& w1, const arma::vec& w2, const arma::vec& dep);
RcppExport SEXP _gaugeDependence_gauss_gauge(SEXP w1SEXP, SEXP w2SEXP, SEXP depSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dep(depSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_gauge(w1, w2, dep));
    return rcpp_result_gen;
END_RCPP
}
// inv_log_gauge
arma::vec inv_log_gauge(const arma::vec& w1, const arma::vec& w2, const arma::vec& dep);
RcppExport SEXP _gaugeDependence_inv_log_gauge(SEXP w1SEXP, SEXP w2SEXP, SEXP depSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dep(depSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_log_gauge(w1, w2, dep));
    return rcpp_result_gen;
END_RCPP
}
// rectangular_gauge
arma::vec rectangular_gauge(const arma::vec& w1, const arma::vec& w2, const arma::vec& dep);
RcppExport SEXP _gaugeDependence_rectangular_gauge(SEXP w1SEXP, SEXP w2SEXP, SEXP depSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dep(depSEXP);
    rcpp_result_gen = Rcpp::wrap(rectangular_gauge(w1, w2, dep));
    return rcpp_result_gen;
END_RCPP
}
// logistic_gauge
arma::vec logistic_gauge(const arma::vec& w1, const arma::vec& w2, const arma::vec& dep);
RcppExport SEXP _gaugeDependence_logistic_gauge(SEXP w1SEXP, SEXP w2SEXP, SEXP depSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dep(depSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_gauge(w1, w2, dep));
    return rcpp_result_gen;
END_RCPP
}
// asym_log_gauge
arma::vec asym_log_gauge(const arma::vec& w1, const arma::vec& w2, const arma::vec& dep);
RcppExport SEXP _gaugeDependence_asym_log_gauge(SEXP w1SEXP, SEXP w2SEXP, SEXP depSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dep(depSEXP);
    rcpp_result_gen = Rcpp::wrap(asym_log_gauge(w1, w2, dep));
    return rcpp_result_gen;
END_RCPP
}
// dirichlet_gauge
arma::vec dirichlet_gauge(const arma::vec& w1, const arma::vec& w2, const arma::vec& dep);
RcppExport SEXP _gaugeDependence_dirichlet_gauge(SEXP w1SEXP, SEXP w2SEXP, SEXP depSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dep(depSEXP);
    rcpp_result_gen = Rcpp::wrap(dirichlet_gauge(w1, w2, dep));
    return rcpp_result_gen;
END_RCPP
}
// calc_loglik_angular
arma::mat calc_loglik_angular(const arma::vec& angles, const arma::mat& grid_x, const int& dim, const arma::mat& posterior_params, const std::string& gauge_type);
RcppExport SEXP _gaugeDependence_calc_loglik_angular(SEXP anglesSEXP, SEXP grid_xSEXP, SEXP dimSEXP, SEXP posterior_paramsSEXP, SEXP gauge_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type angles(anglesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type grid_x(grid_xSEXP);
    Rcpp::traits::input_parameter< const int& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type posterior_params(posterior_paramsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type gauge_type(gauge_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_loglik_angular(angles, grid_x, dim, posterior_params, gauge_type));
    return rcpp_result_gen;
END_RCPP
}
// calc_loglik_radial
arma::mat calc_loglik_radial(const arma::vec& radii, const arma::vec& r0w, const arma::vec& angles, const arma::mat& posterior_params, const std::string& likelihood_type, const std::string& gauge_type);
RcppExport SEXP _gaugeDependence_calc_loglik_radial(SEXP radiiSEXP, SEXP r0wSEXP, SEXP anglesSEXP, SEXP posterior_paramsSEXP, SEXP likelihood_typeSEXP, SEXP gauge_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r0w(r0wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type angles(anglesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type posterior_params(posterior_paramsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type likelihood_type(likelihood_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type gauge_type(gauge_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_loglik_radial(radii, r0w, angles, posterior_params, likelihood_type, gauge_type));
    return rcpp_result_gen;
END_RCPP
}
// radial_adaptive_mh
Rcpp::List radial_adaptive_mh(const arma::vec& radii, const arma::vec& r0w, const arma::vec& angles, const arma::rowvec& starting_theta, const std::string& likelihood_type, const std::string& gauge_type, Rcpp::Nullable<Rcpp::NumericMatrix> prop_Sigma_, const int& n_updates, const int& update_freq, const int& n_burnin, const int& n_thin, const bool& adapt_cov, const double& r_opt, const double& c0, const double& c1, const int& K);
RcppExport SEXP _gaugeDependence_radial_adaptive_mh(SEXP radiiSEXP, SEXP r0wSEXP, SEXP anglesSEXP, SEXP starting_thetaSEXP, SEXP likelihood_typeSEXP, SEXP gauge_typeSEXP, SEXP prop_Sigma_SEXP, SEXP n_updatesSEXP, SEXP update_freqSEXP, SEXP n_burninSEXP, SEXP n_thinSEXP, SEXP adapt_covSEXP, SEXP r_optSEXP, SEXP c0SEXP, SEXP c1SEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r0w(r0wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type angles(anglesSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type starting_theta(starting_thetaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type likelihood_type(likelihood_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type gauge_type(gauge_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type prop_Sigma_(prop_Sigma_SEXP);
    Rcpp::traits::input_parameter< const int& >::type n_updates(n_updatesSEXP);
    Rcpp::traits::input_parameter< const int& >::type update_freq(update_freqSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_burnin(n_burninSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_thin(n_thinSEXP);
    Rcpp::traits::input_parameter< const bool& >::type adapt_cov(adapt_covSEXP);
    Rcpp::traits::input_parameter< const double& >::type r_opt(r_optSEXP);
    Rcpp::traits::input_parameter< const double& >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const double& >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(radial_adaptive_mh(radii, r0w, angles, starting_theta, likelihood_type, gauge_type, prop_Sigma_, n_updates, update_freq, n_burnin, n_thin, adapt_cov, r_opt, c0, c1, K));
    return rcpp_result_gen;
END_RCPP
}
// est_star_vol
double est_star_vol(const arma::mat& grid_x, const arma::vec& pars, const std::string& ang_gauge_type);
RcppExport SEXP _gaugeDependence_est_star_vol(SEXP grid_xSEXP, SEXP parsSEXP, SEXP ang_gauge_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type grid_x(grid_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ang_gauge_type(ang_gauge_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(est_star_vol(grid_x, pars, ang_gauge_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gaugeDependence_angular_vol_adaptive_mh", (DL_FUNC) &_gaugeDependence_angular_vol_adaptive_mh, 15},
    {"_gaugeDependence_gauss_gauge", (DL_FUNC) &_gaugeDependence_gauss_gauge, 3},
    {"_gaugeDependence_inv_log_gauge", (DL_FUNC) &_gaugeDependence_inv_log_gauge, 3},
    {"_gaugeDependence_rectangular_gauge", (DL_FUNC) &_gaugeDependence_rectangular_gauge, 3},
    {"_gaugeDependence_logistic_gauge", (DL_FUNC) &_gaugeDependence_logistic_gauge, 3},
    {"_gaugeDependence_asym_log_gauge", (DL_FUNC) &_gaugeDependence_asym_log_gauge, 3},
    {"_gaugeDependence_dirichlet_gauge", (DL_FUNC) &_gaugeDependence_dirichlet_gauge, 3},
    {"_gaugeDependence_calc_loglik_angular", (DL_FUNC) &_gaugeDependence_calc_loglik_angular, 5},
    {"_gaugeDependence_calc_loglik_radial", (DL_FUNC) &_gaugeDependence_calc_loglik_radial, 6},
    {"_gaugeDependence_radial_adaptive_mh", (DL_FUNC) &_gaugeDependence_radial_adaptive_mh, 16},
    {"_gaugeDependence_est_star_vol", (DL_FUNC) &_gaugeDependence_est_star_vol, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gaugeDependence(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
