# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

angular_vol_adaptive_mh <- function(angles, grid_x, dim, starting_theta, gauge_type, prop_Sigma_ = NULL, n_updates = 10000L, update_freq = 100L, n_burnin = 0L, n_thin = 1L, adapt_cov = FALSE, r_opt = 0.234, c0 = 10, c1 = 0.8, K = 10L) {
    .Call(`_gaugeDependence_angular_vol_adaptive_mh`, angles, grid_x, dim, starting_theta, gauge_type, prop_Sigma_, n_updates, update_freq, n_burnin, n_thin, adapt_cov, r_opt, c0, c1, K)
}

gauss_gauge <- function(w1, w2, dep) {
    .Call(`_gaugeDependence_gauss_gauge`, w1, w2, dep)
}

inv_log_gauge <- function(w1, w2, dep) {
    .Call(`_gaugeDependence_inv_log_gauge`, w1, w2, dep)
}

rectangular_gauge <- function(w1, w2, dep) {
    .Call(`_gaugeDependence_rectangular_gauge`, w1, w2, dep)
}

logistic_gauge <- function(w1, w2, dep) {
    .Call(`_gaugeDependence_logistic_gauge`, w1, w2, dep)
}

asym_log_gauge <- function(w1, w2, dep) {
    .Call(`_gaugeDependence_asym_log_gauge`, w1, w2, dep)
}

dirichlet_gauge <- function(w1, w2, dep) {
    .Call(`_gaugeDependence_dirichlet_gauge`, w1, w2, dep)
}

radial_adaptive_mh <- function(radii, r0w, angles, starting_theta, likelihood_type, gauge_type, prop_Sigma_ = NULL, n_updates = 10000L, update_freq = 100L, n_burnin = 0L, n_thin = 1L, adapt_cov = FALSE, r_opt = 0.234, c0 = 10, c1 = 0.8, K = 10L) {
    .Call(`_gaugeDependence_radial_adaptive_mh`, radii, r0w, angles, starting_theta, likelihood_type, gauge_type, prop_Sigma_, n_updates, update_freq, n_burnin, n_thin, adapt_cov, r_opt, c0, c1, K)
}

est_star_vol <- function(grid_x, pars, ang_gauge_type) {
    .Call(`_gaugeDependence_est_star_vol`, grid_x, pars, ang_gauge_type)
}

